"""Stage 2 — synthesise identity-consistent age sequences with FLUX.1-schnell.

THIS FILE IS THE MOAT. Read the reasoning before changing it.

The problem
-----------
Every open re-aging model traces back to FFHQ + StyleGAN + SAM. NVIDIA's
StyleGAN material is CC BY-NC 4.0 and FFHQ is non-commercial. Weights trained
on that lineage cannot be sold. That's why this space is empty despite the
research being 4 years old.

The obvious fix -- FLUX + an identity adapter (PuLID / InstantID) -- reintroduces
the problem through the back door, because those adapters depend on InsightFace
antelopev2 for the ID embedding, which is non-commercial. FLUX.1-Kontext is
likewise under the non-commercial FLUX.1 [dev] licence. Only FLUX.1-schnell is
Apache 2.0.

The fix that actually works
---------------------------
Skip the ID adapter entirely. Exploit two facts:

  1. FLUX with a FIXED SEED and a FIXED INITIAL LATENT produces a highly
     correlated image when you change only a few tokens of the prompt. Swap
     just the age phrase and you often get the same person, older.
  2. Offline compute is free. The user's GPU, running overnight, costs nothing.

So: over-generate, then filter ruthlessly (stage 3). If only 20% of sequences
hold identity, we throw away 80% and lose nothing but wall-clock. Yield is
irrelevant when the marginal cost is zero. Brute force + a strict identity
threshold beats a legally-encumbered adapter.

Result: every pixel of training data is generated by an Apache-2.0 model from
prompts we wrote. Clean parentage, defensible, sellable.

Usage:
    python -m agecraft.data.generate_pairs \
        --prompts data/prompts.jsonl --out data/raw --limit 4000
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import torch

# Age anchors for each identity sequence. Deliberately adult-only: the product
# is a re-aging tool for consenting adults, and a model that never saw a child
# cannot be trivially steered to produce one. This is a design decision, not an
# oversight -- see PROVENANCE.md and the consent gate in the app layer.
DEFAULT_ANCHORS = [20, 30, 40, 50, 60, 70, 80]

# Age phrasing. Kept as an explicit table so the age signal is consistent and
# auditable rather than whatever the LLM felt like that day.
# MEASURED FINDING: keep these SHORT and about SKIN/HAIR ONLY.
#
# v1 used "full cheeks" at 20 and "hollow cheeks" at 80. Those are face-SHAPE
# descriptors -- they change bone/fat geometry, so FLUX drew a genuinely
# rounder or gaunter face and FaceNet correctly called it a different person.
# The evidence was unmistakable in the adjacent-similarity chains:
#     id_000039  [0.26, 0.59, 0.90, 0.91]
#     id_000022  [0.35, 0.78, 0.87, 0.84]
#     id_000020  [0.41, 0.73, 0.94, 0.96]
# The 20->35 link breaks while 50->65->80 holds at 0.9+, because the older
# phrases only described skin and hair. Shape language was the drift.
#
# Volume loss and sagging are real ageing signals we DO want the delta net to
# learn -- but it learns them from pixels, not from us instructing FLUX to
# redraw the skull. Let ageing emerge from skin/hair cues.
#
# LENGTH ALSO MATTERS: CLIP truncates at 77 tokens and the age phrase is
# appended LAST, so it gets cut first. Observed in the v1 run:
#     "truncated ... ['grey hair']"  "truncated ... ['white sparse hair']"
# T5 still saw the full prompt so the signal survived, but CLIP's pooled
# embedding lost it. Short phrases keep the age inside both encoders' windows.
AGE_PHRASES = {
    20: "aged 20, smooth unlined skin",
    30: "aged 30, faint expression lines",
    35: "aged 35, faint expression lines",
    40: "aged 40, light forehead lines",
    50: "aged 50, visible wrinkles, some grey hair",
    60: "aged 60, deep wrinkles, mostly grey hair",
    65: "aged 65, deep wrinkles, grey-white hair",
    70: "aged 70, heavily lined skin, white hair, age spots",
    80: "aged 80, deeply creased thin skin, white sparse hair",
}

MODEL_ID = "black-forest-labs/FLUX.1-schnell"  # Apache 2.0. Do not swap for [dev].

# VRAM reality check. FLUX.1-schnell at bf16 is ~33.6GB total:
#   T5-XXL 9.4GB | CLIP-L 0.2GB | MMDiT transformer 23.8GB | VAE 0.2GB
#
# enable_model_cpu_offload() keeps the LARGEST SINGLE MODULE resident, i.e. the
# 23.8GB transformer. That needs a 24GB+ card. It was the original default here
# and it OOMs on anything smaller -- a real bug, now fixed.
#
#   >=24GB (4090/A100)  : mode="offload",    no quantization    ~1.2 s/img @768
#   16GB   (T4/P100)    : mode="offload",    quantize="nf4"     ~20  s/img @768
#   8-12GB (3060/4070)  : mode="sequential", quantize="nf4"     ~60  s/img @768
#   <8GB   (GTX 1650)   : NOT VIABLE. 4-bit transformer alone is 6.5GB.
#                         Sequential offload "works" at minutes/image, which
#                         means months for a real dataset. Use Kaggle or rent.
MIN_VRAM_GB = {"offload": 24.0, "offload_nf4": 12.0, "sequential_nf4": 6.0}


def build_pipeline(mode: str = "offload", quantize: str | None = None,
                   dtype: str = "bf16"):
    """Build the FLUX pipeline for the available hardware.

    dtype: bf16 on Ampere+; T4/P100 are pre-Ampere and lack bf16 -> use fp16.
    """
    import torch
    from diffusers import FluxPipeline

    td = {"bf16": torch.bfloat16, "fp16": torch.float16}[dtype]

    if torch.cuda.is_available():
        free_gb = torch.cuda.get_device_properties(0).total_memory / 1e9
        key = f"{mode}_{quantize}" if quantize else mode
        need = MIN_VRAM_GB.get(key, 24.0)
        print(f"[vram] {torch.cuda.get_device_name(0)}: {free_gb:.1f}GB "
              f"| mode={mode} quantize={quantize} needs ~{need:.0f}GB")
        if free_gb < need:
            print(f"[vram] WARNING: likely OOM. See the table in this file.")

    if quantize == "nf4":
        from diffusers import BitsAndBytesConfig as DiffBnb
        from diffusers import FluxTransformer2DModel
        from transformers import BitsAndBytesConfig as TfBnb
        from transformers import T5EncoderModel

        dq = DiffBnb(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                     bnb_4bit_compute_dtype=td)
        transformer = FluxTransformer2DModel.from_pretrained(
            MODEL_ID, subfolder="transformer", quantization_config=dq, torch_dtype=td)

        tq = TfBnb(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                   bnb_4bit_compute_dtype=td)
        text_encoder_2 = T5EncoderModel.from_pretrained(
            MODEL_ID, subfolder="text_encoder_2", quantization_config=tq,
            torch_dtype=td)

        pipe = FluxPipeline.from_pretrained(
            MODEL_ID, transformer=transformer, text_encoder_2=text_encoder_2,
            torch_dtype=td)
    else:
        pipe = FluxPipeline.from_pretrained(MODEL_ID, torch_dtype=td)

    if mode == "offload":
        pipe.enable_model_cpu_offload()
    elif mode == "sequential":
        pipe.enable_sequential_cpu_offload()  # fits tiny VRAM, brutally slow
    elif mode == "cuda":
        pipe.to("cuda")
    else:
        raise ValueError(f"unknown mode: {mode}")

    pipe.set_progress_bar_config(disable=True)
    return pipe


def compose(base_prompt: str, age: int) -> str:
    return f"{base_prompt}, {AGE_PHRASES[age]}"


def generate_sequence(pipe, spec: dict, out_dir: Path, steps: int, size: int,
                      anchors: list[int], dtype) -> dict:
    """Generate one identity across all age anchors, seed- and latent-locked.

    THE SEED LOCK: we build the initial latent ONCE from the identity's seed and
    reuse the identical tensor for every age. Passing a fresh Generator per call
    is NOT equivalent -- diffusers advances generator state, so ages would drift
    to different people. Locking the latent is what makes the same face come out
    the other side. Measured: 72% of sequences hold identity (min-adjacent
    cosine >= 0.55) with no ID adapter at all.

    THE BATCHING: all anchors go through ONE pipe call as a batch, sharing the
    same repeated latent. This is not cosmetic -- with enable_model_cpu_offload()
    the 23.8GB transformer crosses PCIe once per *call*, so per-image calls cost
    ~33GB of transfers each and measured 17.4s/image (sys time was 44m of a 71m
    run: that's bus traffic, not compute). Batching amortises one transfer over
    all anchors. Mathematically identical output -- each batch row uses its own
    latent row, and they're all copies of the same tensor.
    """
    ident = spec["id"]
    seq_dir = out_dir / ident
    seq_dir.mkdir(parents=True, exist_ok=True)

    paths = {age: seq_dir / f"{age:03d}.png" for age in anchors}
    if all(p.exists() for p in paths.values()):  # resumable
        return {**spec, "frames": {str(a): str(p) for a, p in paths.items()}}

    # FLUX packs latents to 1/8 spatial with 16 channels.
    latent_h, latent_w = size // 8, size // 8
    gen = torch.Generator(device="cpu").manual_seed(spec["seed"])
    latents = torch.randn((1, 16, latent_h, latent_w), generator=gen, dtype=dtype)
    # diffusers expects packed latents for FLUX: (B, H/2*W/2, C*4)
    latents = latents.view(1, 16, latent_h // 2, 2, latent_w // 2, 2)
    latents = latents.permute(0, 2, 4, 1, 3, 5).reshape(
        1, (latent_h // 2) * (latent_w // 2), 64
    )

    prompts = [compose(spec["prompt"], age) for age in anchors]
    images = pipe(
        prompt=prompts,
        height=size,
        width=size,
        num_inference_steps=steps,       # schnell is distilled: 4 is enough
        guidance_scale=0.0,              # schnell is guidance-distilled
        latents=latents.repeat(len(anchors), 1, 1),  # <-- same lock, batched
    ).images

    record = {**spec, "frames": {}}
    for age, img in zip(anchors, images):
        img.save(paths[age])
        record["frames"][str(age)] = str(paths[age])
    return record


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--prompts", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--steps", type=int, default=4)
    ap.add_argument("--size", type=int, default=768)
    ap.add_argument("--mode", default="offload",
                    choices=["offload", "sequential", "cuda"])
    ap.add_argument("--quantize", default=None, choices=[None, "nf4"])
    ap.add_argument("--dtype", default="bf16", choices=["bf16", "fp16"],
                    help="fp16 for T4/P100 (pre-Ampere, no bf16 support)")
    ap.add_argument("--anchors", default="20,30,40,50,60,70,80",
                    help="age anchors; use 20,35,50,65,80 to cut cost by 30%%")
    args = ap.parse_args()

    anchors = [int(a) for a in args.anchors.split(",")]
    bad = [a for a in anchors if a not in AGE_PHRASES]
    if bad:
        raise SystemExit(f"no phrasing for ages {bad}; known: {sorted(AGE_PHRASES)}")
    if min(anchors) < 20:
        raise SystemExit("age anchors below 20 are refused by design; see PROVENANCE.md")

    specs = [json.loads(l) for l in args.prompts.read_text().splitlines() if l.strip()]
    if args.limit:
        specs = specs[: args.limit]

    args.out.mkdir(parents=True, exist_ok=True)
    pipe = build_pipeline(mode=args.mode, quantize=args.quantize, dtype=args.dtype)
    dtype = {"bf16": torch.bfloat16, "fp16": torch.float16}[args.dtype]

    manifest = args.out / "manifest.jsonl"
    done = set()
    if manifest.exists():
        done = {json.loads(l)["id"] for l in manifest.read_text().splitlines() if l.strip()}
        print(f"resuming, {len(done)} sequences already done")

    t0 = time.time()
    n_new = 0
    with manifest.open("a") as mf:
        for i, spec in enumerate(specs):
            if spec["id"] in done:
                continue
            rec = generate_sequence(pipe, spec, args.out, args.steps, args.size,
                                    anchors, dtype)
            mf.write(json.dumps(rec) + "\n")
            mf.flush()
            n_new += 1
            if n_new % 5 == 0:
                per = (time.time() - t0) / (n_new * len(anchors))
                left = (len(specs) - i - 1) * len(anchors) * per
                print(f"  {i+1}/{len(specs)} identities | {per:.1f}s/image | "
                      f"ETA {left/3600:.1f}h")

    print(f"done -> {manifest}")
    print("NOTE: raw sequences are UNFILTERED. Run filter_pairs.py next -- "
          "expect to discard 60-80%. That is the design working, not failing.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
